# Generated by Django 4.2.4 on 2023-08-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('submit_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('national_id_card', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_date', models.DateTimeField()),
                ('winner_ballot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lottery.ballot')),
            ],
        ),
        migrations.AddField(
            model_name='ballot',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lottery.participant'),
        ),
    ]
