# Generated by Django 4.2.4 on 2023-08-05 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 12, 53, 52, 686050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lottery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 12, 53, 52, 686794, tzinfo=datetime.timezone.utc)),
        ),
    ]
