# Generated by Django 4.2.4 on 2023-08-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_remove_ballot_submit_date_ballot_lottery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='lottery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lottery.participant'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lottery_date',
            field=models.DateField(),
        ),
    ]
