# Generated by Django 4.2.4 on 2023-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_alter_ballot_lottery_date_alter_ballot_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='id',
        ),
        migrations.AlterField(
            model_name='lottery',
            name='lottery_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
